---
- name: Install and configure nginx, php and database
  hosts: 192.168.56.108
  become: true
  vars:
    packages:
          - php7.4-mysql
          - php7.4-curl
          - php7.4-json
          - php7.4-cgi
          - php7.4-xsl
          - php7.4-cgi
          - php7.4-gd
          - php7.4-mbstring
          - php7.4-zip
          - php7.4-xmlrpc
          - php7.4-soap
          - php7.4-intl
          - libapache2-mod-php


  tasks:
    - name: Installing Nginx
      apt:
        name: nginx
        state: present

    - name: Installation install software-properties-common
      apt: name=software-properties-common

    - name: "Repo PHP 7.4"
      apt_repository:
        repo="ppa:ondrej/php"

    - name: "Updating the repo"
      apt: update_cache=yes

   
    - name: Installation PHP 7.4
      apt: name=php7.4 state=present

    - name: install lamp stack packages
      apt:
        pkg: "{{ packages }}"
        state: present
        update_cache: yes


 - name: Install MySQL
      apt:
        name: mysql-server
        state: present

    - name: Allow incoming connections on port 80
      ufw:
        rule: allow
        port: 80

    - name: Copy Nginx sites-enabled file
      copy:
        src: /root/website/ansible-playground/default
        dest: /etc/nginx/sites-enabled/default
        owner: root
        group: root
        mode: "0644"
      notify:
        - Restart Nginx

    - name: Copy Nginx sites-available file
      copy:
        src: /root/website/ansible-playground/default
        dest: /etc/nginx/sites-available/default
 - name: Copy Nginx sites-available file
      copy:
        src: /root/website/ansible-playground/default
        dest: /etc/nginx/sites-available/default
        owner: root
        group: root
        mode: "0644"
      notify:
        - Restart Nginx

    - name: Copy web files to /var/www/html
      copy:
        src: /root/website/ansible-playground/wave_cafe
        dest: /var/www/html/wave_cafe
        owner: root
        group: root
        mode: "0755"

  handlers:
    - name: Restart Nginx
      service:
        name: nginx

